version: '3.7'
services:
  jenkins:
    image: jenkins/jenkins:lts
    restart: unless-stopped
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    volumes:
      - ~/jenkins:/var/jenkins_home

  agent:
    image: jenkins/ssh-agent:jdk11
    restart: unless-stopped
    privileged: true
    user: root
    container_name: agent
    expose:
      - 22
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIISvv6oZCBsaj/+vSF4V5/SDPgf+5IVlLbIqwQdMjK3r greengoo@greengoo-pc